base: --no-source --color --format pretty -p html_report
default: --profile local 

local: --profile base PROFILE=local
qa: --profile base PROFILE=qa


html_report: --format progress --format html --out=report/features_report.html
bvt: --tags @bvt

json_report: --format json --out=report/features_report.json